name: renner_coatings
description: Aplicativo com acesso as principais informações da Renner Coatigns como catálogo de
  produtos, lista de preços, lista de cotação, push notifications, catálogo de cores, distribuidores e revendas.
author: Fernando Alexandre Wahl / Astéria Internet Solutions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.6
  flutter_launcher_icons: ^0.9.1
  cupertino_icons: ^1.0.3
  mask_text_input_formatter: ^2.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  http: ^0.13.3
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^9.1.0
  cpf_cnpj_validator: ^2.0.0
  whatsapp_unilink: ^2.0.0
  url_launcher: ^6.0.10
  geolocator: ^7.6.2
  location: ^4.3.0
  connectivity_plus: ^1.1.0
  background_fetch: ^1.0.1
  permission_handler: ^8.1.6
  open_file: ^3.2.1
  path_provider: ^2.0.5
  google_maps_widget: ^0.0.8

dev_dependencies:
  #flutter_test:
  #  sdk: flutter


flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path_android: 'assets/icons/icone.png'
  image_path_ios: 'assets/icons/icone.png'


flutter:
  uses-material-design: true

  assets:
    - assets/icons/icone.png
    - assets/icons/icon_whatsapp.png
    - assets/icons/brasil_flag.png
    - assets/icons/chile_flag.png
    - assets/icons/peru_flag.png
    - assets/images/logo_renner.png
    - assets/images/tintas.png
    - assets/images/
    - assets/icons/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: fonts/helveticaneue-medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
